# Generated by Django 2.0.2 on 2021-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='project_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='project_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
