# Generated by Django 2.0.2 on 2019-08-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('body', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='image/blogimages/')),
            ],
        ),
    ]
